# Generated by Django 5.1.2 on 2024-10-26 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etat', models.CharField(choices=[('ON', 'Allumé'), ('OFF', 'Éteint')], max_length=3)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('heure_allumage', models.DateTimeField(blank=True, null=True)),
                ('heure_extinction', models.DateTimeField(blank=True, null=True)),
                ('temps_ecoule', models.DurationField(blank=True, null=True)),
                ('groupe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='api.groupeelectrogene')),
                ('previous_on_action', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_off_actions', to='api.action')),
            ],
        ),
    ]
