# Generated by Django 5.1.2 on 2024-10-26 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='gardien',
            name='groupe_associe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gardiens', to='api.groupeelectrogene'),
        ),
        migrations.AlterField(
            model_name='gardien',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='gardien',
            name='nom',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='gardien',
            name='prenom',
            field=models.CharField(max_length=50),
        ),
    ]
