# Generated by Django 5.1.2 on 2024-10-26 16:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_action_gardien'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='gardien',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions_allumage', to='api.gardien'),
        ),
    ]
